import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/transaction_model.dart';
import '../providers/transaction_provider.dart';

class PdfService {
  // ── Colour helpers ─────────────────────────────────────────────
  static const _gold = PdfColor.fromInt(0xFF9E7E38);
  static const _goldLight = PdfColor.fromInt(0xFFF5EDDA);
  static const _inkDark = PdfColor.fromInt(0xFF1A1A1A);
  static const _inkMid = PdfColor.fromInt(0xFF4A453C);
  static const _inkLight = PdfColor.fromInt(0xFFA6A29A);
  static const _green = PdfColor.fromInt(0xFF22C55E);
  static const _red = PdfColor.fromInt(0xFFE11D48);
  static const _bg = PdfColor.fromInt(0xFFFDFBF7);
  static const _surface = PdfColor.fromInt(0xFFF2EEE7);
  static const _border = PdfColor.fromInt(0xFFD1CEC4);

  static String _fmt(double v) {
    if (v >= 100000) return '${(v / 100000).toStringAsFixed(1)}L';
    if (v >= 1000) return '${(v / 1000).toStringAsFixed(1)}K';
    return v.toStringAsFixed(2);
  }

  /// Generate a monthly statement PDF and return raw bytes.
  static Future<Uint8List> generateMonthlyStatement(
    TransactionProvider provider,
    DateTime month,
  ) async {
    final pdf = pw.Document(
      author: provider.userName,
      title: 'Fin Tracker — ${DateFormat('MMMM yyyy').format(month)}',
    );

    final txns = provider.transactions
        .where((t) => t.date.year == month.year && t.date.month == month.month)
        .toList()
      ..sort((a, b) => a.date.compareTo(b.date));

    final income = txns
        .where((t) => t.type == TransactionType.income)
        .fold(0.0, (s, t) => s + t.amount);
    final expenses = txns
        .where((t) => t.type == TransactionType.expense)
        .fold(0.0, (s, t) => s + t.amount);
    final net = income - expenses;

    // Category breakdown
    final breakdown = <String, double>{};
    for (final t in txns.where((t) => t.type == TransactionType.expense)) {
      breakdown[t.category] = (breakdown[t.category] ?? 0) + t.amount;
    }
    final sortedCats = breakdown.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        theme: pw.ThemeData.withFont(
          base: pw.Font.helvetica(),
          bold: pw.Font.helveticaBold(),
          italic: pw.Font.helveticaOblique(),
        ),
        build: (ctx) => [
          // ── Cover Header ──────────────────────────────────────────
          _buildHeader(provider.userName, month),
          pw.SizedBox(height: 24),

          // ── Summary Cards ─────────────────────────────────────────
          _buildSummaryRow(income, expenses, net),
          pw.SizedBox(height: 24),

          // ── Category Breakdown ────────────────────────────────────
          if (sortedCats.isNotEmpty) ...[
            _sectionTitle('Expense Breakdown'),
            pw.SizedBox(height: 10),
            _buildCategoryTable(sortedCats, expenses),
            pw.SizedBox(height: 24),
          ],

          // ── Transactions Table ────────────────────────────────────
          _sectionTitle('All Transactions'),
          pw.SizedBox(height: 10),
          if (txns.isEmpty)
            pw.Text('No transactions this month.',
                style: const pw.TextStyle(color: _inkLight))
          else
            _buildTransactionsTable(txns),

          // ── Footer note ───────────────────────────────────────────
          pw.SizedBox(height: 20),
          pw.Divider(color: _border),
          pw.SizedBox(height: 6),
          pw.Text(
            'Generated by Fin Tracker • ${DateFormat('dd MMM yyyy, hh:mm a').format(DateTime.now())}',
            style: pw.TextStyle(color: _inkLight, fontSize: 9, fontStyle: pw.FontStyle.italic),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  // ── Sub-builders ───────────────────────────────────────────────

  static pw.Widget _buildHeader(String name, DateTime month) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(20),
      decoration: const pw.BoxDecoration(
        color: _gold,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(12)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('Fin Tracker',
                  style: pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 22,
                      fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text('Monthly Statement',
                  style: const pw.TextStyle(color: PdfColors.white, fontSize: 12)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(DateFormat('MMMM yyyy').format(month),
                  style: pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 16,
                      fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text(name,
                  style: const pw.TextStyle(color: PdfColors.white, fontSize: 11)),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSummaryRow(double income, double expenses, double net) {
    return pw.Row(
      children: [
        pw.Expanded(child: _summaryCard('Total Income', 'Rs.${_fmt(income)}', _green)),
        pw.SizedBox(width: 12),
        pw.Expanded(child: _summaryCard('Total Expenses', 'Rs.${_fmt(expenses)}', _red)),
        pw.SizedBox(width: 12),
        pw.Expanded(
          child: _summaryCard(
            'Net Balance',
            'Rs.${_fmt(net.abs())}',
            net >= 0 ? _green : _red,
          ),
        ),
      ],
    );
  }

  static pw.Widget _summaryCard(String label, String value, PdfColor color) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: _surface,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
        border: pw.Border.all(color: _border),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label,
              style: const pw.TextStyle(color: _inkLight, fontSize: 10)),
          pw.SizedBox(height: 4),
          pw.Text(value,
              style: pw.TextStyle(
                  color: color, fontSize: 16, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  static pw.Widget _sectionTitle(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: const pw.BoxDecoration(
        color: _goldLight,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Text(title,
          style: pw.TextStyle(
              color: _gold, fontSize: 12, fontWeight: pw.FontWeight.bold)),
    );
  }

  static pw.Widget _buildCategoryTable(
      List<MapEntry<String, double>> cats, double total) {
    final headers = ['Category', 'Amount', '% of Total'];
    final rows = cats.map((e) {
      final pct = total > 0 ? (e.value / total * 100).toStringAsFixed(1) : '0.0';
      return [e.key, 'Rs.${_fmt(e.value)}', '$pct%'];
    }).toList();

    return pw.Table(
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(1.5),
        2: const pw.FlexColumnWidth(1),
      },
      border: pw.TableBorder.all(color: _border, width: 0.5),
      children: [
        // Header row
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _surface),
          children: headers.map((h) => _tableCell(h, isHeader: true)).toList(),
        ),
        ...rows.asMap().entries.map((entry) {
          final isEven = entry.key % 2 == 0;
          return pw.TableRow(
            decoration: pw.BoxDecoration(color: isEven ? _bg : PdfColors.white),
            children: entry.value.map((c) => _tableCell(c)).toList(),
          );
        }),
      ],
    );
  }

  static pw.Widget _buildTransactionsTable(List<TransactionModel> txns) {
    final headers = ['Date', 'Category', 'Notes', 'Type', 'Amount'];
    final rows = txns.map((t) {
      return [
        DateFormat('dd MMM').format(t.date),
        t.category,
        t.notes.isNotEmpty ? t.notes : '—',
        t.type == TransactionType.income ? 'Income' : 'Expense',
        '${t.type == TransactionType.income ? '+' : '-'}Rs.${_fmt(t.amount)}',
      ];
    }).toList();

    return pw.Table(
      columnWidths: {
        0: const pw.FlexColumnWidth(1.2),
        1: const pw.FlexColumnWidth(1.5),
        2: const pw.FlexColumnWidth(2),
        3: const pw.FlexColumnWidth(1.2),
        4: const pw.FlexColumnWidth(1.5),
      },
      border: pw.TableBorder.all(color: _border, width: 0.5),
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _surface),
          children: headers.map((h) => _tableCell(h, isHeader: true)).toList(),
        ),
        ...rows.asMap().entries.map((entry) {
          final i = entry.key;
          final row = entry.value;
          final isIncome = txns[i].type == TransactionType.income;
          return pw.TableRow(
            decoration: pw.BoxDecoration(color: i % 2 == 0 ? _bg : PdfColors.white),
            children: row.asMap().entries.map((cellEntry) {
              final isAmountCol = cellEntry.key == 4;
              final isTypeCol = cellEntry.key == 3;
              PdfColor? color;
              if (isAmountCol || isTypeCol) color = isIncome ? _green : _red;
              return _tableCell(cellEntry.value, textColor: color);
            }).toList(),
          );
        }),
      ],
    );
  }

  static pw.Widget _tableCell(String text,
      {bool isHeader = false, PdfColor? textColor}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: isHeader ? 10 : 9,
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: textColor ?? (isHeader ? _inkDark : _inkMid),
        ),
        overflow: pw.TextOverflow.clip,
      ),
    );
  }
}
